### ISSUE TITLE
Upload File?

### ISSUE THREAD

**Issue by testdroid11571157** [awslabs/aws-sdk-xamarin#13]
I have tried uploading files in Xamarin but am having no success. I have tried transfer utility to no avail. Are there any guides for this in Xamarin? I tried using .NET documentation and android guides but they didnt seem to help.

The following code runs after a button click:

```javascript
string filePath = App._dir.AbsolutePath + "/" + "testkey" + ".mp4";

Java.IO.File file = new Java.IO.File(filePath);
				if(!file.Exists())  return false;

var transferRequest = new TransferUtilityUploadRequest
				{
					Key = "testkey.mp4",
					FilePath = filePath,
					BucketName = "testBucket/testSub",
					ContentType = "video/mp4",
				};

AmazonS3Config config = new AmazonS3Config();
config.ServiceURL = "s3.amazonaws.com";
			config.UseHttp = true;
			config.RegionEndpoint = Amazon.RegionEndpoint.USEast1;

amazonS3Client = new Amazon.S3.AmazonS3Client (keyId, secretKey, config)
				System.Threading.CancellationToken cancellationToken = new System.Threading.CancellationToken();

				TransferUtility transferUtility = new TransferUtility (amazonS3Client);
				transferRequest.UploadProgressEvent += UpdateFileProgress;
				transferUtility.UploadAsync (transferRequest, cancellationToken);


private void UpdateFileProgress(object sender, UploadProgressArgs args)
		{
			// show progress
}

```

Outcome:
returns no errors, returns no code, and does nothing. I have followed the execution path and it goes through many steps including await _s3Client.PutObjectAsync inside simpleUploadCommand in the Amazon Xamarin SDK, but nothing happens. The file exists, the call is made, the key(s) have worked for playback.

*It does not even go into the file progress method.

Can anyone get this to work? Or what is the proper method to upload a file?

Is there any kind of completion or success/failure message to handle or capture upon call completion or error?

Thanks

**Comment by testdroid11571157** [comment]
Any update on this? Its kind of important to upload :+1:

**Comment by tawalke** [comment]
I have been on vacation, I will start back debugging this issue on next week.  I have successfully uploaded, but the issue is intermittent.

Thanks,
TEW

Sent from my Windows Phone
________________________________

**Comment by testdroid11571157** [comment]
Thanks TEW!

**Comment by nilslahr** [comment]
Any luck yet finding this intermittent issue out?  I'm shying away from even playing with the SDK until I know it can upload (and download) without issues.

**Comment by testdroid11571157** [comment]
Is there anything I can do to help solve the issues here? I heavily rely on amazon services an am really close to having to abandon this sdk option if its not working properly soon. Is there an eta on an update or release TEW? Or anything I can do to help solve the issues?

Thanks

**Comment by tawalke** [comment]
Xamarin Beta Version 3 Released today and pushed to GitHub.  Please review and advise regarding any errors.  Please remember that this SDK is still in Beta and your feedback is essential to the enhancement of the SDK.


Thanks!






Sent from Windows Mail





From: testdroid11571157
Sent: ‎Thursday‎, ‎January‎ ‎22‎, ‎2015 ‎4‎:‎56‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Is there anything I can do to help solve the issues here? I heavily rely on amazon services an am really close to having to abandon this sdk option if its not working properly soon. Is there an eta on an update or release TEW? Or anything I can do to help solve the issues?

Thanks

**Comment by testdroid11571157** [comment]
Preliminary test feedback:

Android,

So far so good!  Thanks a ton TEW. I'll update on progress when more data
is available.

**Comment by mzekrallah** [comment]
Hi, I'm still having the same issue discussed above .. I'm using Xamarin.iOS unified compiled binaries .. I just pulled it today .. I'm using the same code above (without setting region endpoint), it completes execution successfully but nothing happens .. no exceptions thrown and S3 bucket is always empty..

However, If I specify the region endpoint in code like this : 
config.RegionEndpoint = Amazon.RegionEndpoint.EUWest1;

I get  stream cannot be null exception thrown on the same line : 

System.ArgumentNullException: Argument cannot be null.
Parameter name: stream
  at System.IO.StreamReader.Initialize (System.IO.Stream stream, System.Text.Encoding encoding, Boolean etectEncodingFromByteOrderMarks, Int32 bufferSize) [0x00006] in 
/Developer/MonoTouch/Source/mono/mcs/class/corlib/System.IO/StreamReader.cs:

201   at System.IO.StreamReader..ctor (System.IO.Stream stream, 
System.Text.Encoding encoding, Boolean etectEncodingFromByteOrderMarks, 
Int32 bufferSize, Boolean leaveOpen) [0x0000e] in /Developer/MonoTouch/Source/mono/mcs/class/corlib/System.IO/StreamReader.cs:
166 
  at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Text.Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) [0x00000] in 
/Developer/MonoTouch/Source/mono/mcs/class/corlib/System.IO/StreamReader.cs:
152 
  at System.IO.StreamReader..ctor (System.IO.Stream stream) [0x00000] in 
/Developer/MonoTouch/Source/mono/mcs/class/corlib/System.IO/StreamR
eader.cs:139   at Amazon.RegionEndpoint.LoadEndpointDefinitionsFromEmbeddedResource () 
[0x00000] in <filename unknown>:0 
  at Amazon.RegionEndpoint.LoadEndpointDefinitions () [0x00000] in <filename 
unknown>:0 
  at Amazon.RegionEndpoint.GetEndpointForService (System.String serviceName) 
[0x00000] in <filename unknown>:0   at Amazon.Runtime.ClientConfig.set_RegionEndpoint (Amazon.RegionEndpoint 
value) [0x00000] in <filename unknown>:0

**Comment by tawalke** [comment]
@testdroid11571157 Were you successful in your upload efforts?

**Comment by tawalke** [comment]
@mzekrallah You have to set the Region Endpoint.  Can you share your code

**Comment by mzekrallah** [comment]
setting the region end point throws a stream cannot be null exception as I specified above. The code used is like this :
string awsAccessKeyID = "";
 string awsSecretAccessKey = "";
            try
            {
                AmazonS3Config config = new AmazonS3Config()
                {
                    ServiceURL = "s3.amazonaws.com",
                    UseHttp = true,
                    RegionEndpoint = Amazon.RegionEndpoint.EUWest1,
                };

                AmazonS3Client client = new AmazonS3Client(awsAccessKeyID, awsSecretAccessKey, config);

                TransferUtility transferUtility = new TransferUtility(client);

                string path = @"Default-568h@2x.png";

                // image path is valid
                UIImage image = UIImage.FromFile(path);

                TransferUtilityUploadRequest request = new TransferUtilityUploadRequest()
                {
                    BucketName = "testtbucket",
                    FilePath = path,
                    ContentType = "image/png",
                    Key = path.GetHashCode().ToString()
                };

                request.UploadProgressEvent += UploadProgressEvent;

                System.Threading.CancellationToken canellationToken = new System.Threading.CancellationToken();

                await transferUtility.UploadAsync(request, canellationToken);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

**Comment by tawalke** [comment]
What is does the image object note as it's  full path./uri?

Sent from my Windows Phone
________________________________

**Comment by mzekrallah** [comment]
sorry, I didn't understand your question. anyway forget the image path, the code doesn't even reach there .. it immediately throws exception on the same line where I set the Region EndPoint.

**Comment by mzekrallah** [comment]
I think the problem is in the setter for the region end point as the stack trace I showed above goes down to this :

Amazon.Runtime.ClientConfig.set_RegionEndpoint (Amazon.RegionEndpoint value) [0x00000

**Comment by tawalke** [comment]
Okay that is very odd if it is RegionEndpoint setter, I will try to reproduce.

Sent from my Windows Phone
________________________________

**Comment by mzekrallah** [comment]
it seems setting the region end point trigger this method LoadEndpointDefinitionsFromEmbeddedResource() and that method opens a stream to load some embedded resources which could throw the stream exception I think .. could this be invalid bundling for resources while building the xamarin iOS Unified api DLL ?

To reproduce just put this code on any Xamarin.iOS Unified API project :

AmazonS3Config config = new AmazonS3Config();
config.ServiceURL = "s3.amazonaws.com",
config.UseHttp = true,
// exception thrown on this line :
config.RegionEndpoint = Amazon.RegionEndpoint.EUWest1,

**Comment by mzekrallah** [comment]
I'm trying to figure it out by reading the internal code so I think GetManifestResourceStream below is returning null in Xamarin.iOS:

        static void LoadEndpointDefinitionsFromEmbeddedResource()
        {
            Assembly assembly = Amazon.Util.TypeFactory.GetTypeInfo(typeof(RegionEndpoint)).Assembly;
            using (StreamReader reader = new StreamReader(assembly.GetManifestResourceStream(REGIONS_FILE)))
            {
                LoadEndpointDefinitions(reader);
            }
        }

Could this help you out ? 

http://stackoverflow.com/questions/18128681/assembly-getmanifestresourcestream-not-working-with-xamarin-on-ios
http://developer.xamarin.com/guides/cross-platform/xamarin-forms/working-with/files/

Appreciate your feedback.

**Comment by tawalke** [comment]
No this is a custom method that was/is working in my sample app code that is running on iOS using this same assembly so I will have to try and figure our why are getting this error.






Sent from Windows Mail





From: mzekrallah
Sent: ‎Monday‎, ‎February‎ ‎23‎, ‎2015 ‎9‎:‎17‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





I'm trying to figure it out by reading the internal code so I think GetManifestResourceStream below is returning null in Xamarin.iOS:
    static void LoadEndpointDefinitionsFromEmbeddedResource()
    {
        Assembly assembly = Amazon.Util.TypeFactory.GetTypeInfo(typeof(RegionEndpoint)).Assembly;
        using (StreamReader reader = new StreamReader(assembly.GetManifestResourceStream(REGIONS_FILE)))
        {
            LoadEndpointDefinitions(reader);
        }
    }


Could this help you out ? 

http://stackoverflow.com/questions/18128681/assembly-getmanifestresourcestream-not-working-with-xamarin-on-ios
http://developer.xamarin.com/guides/cross-platform/xamarin-forms/working-with/files/

Appreciate your feedback.

**Comment by tawalke** [comment]
Out of curiosity, change the region to RegionEndpoint.USEast or USWest and see if you get the same error. 






Sent from Windows Mail





From: mzekrallah
Sent: ‎Monday‎, ‎February‎ ‎23‎, ‎2015 ‎9‎:‎10‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





it seems setting the region end point trigger this method LoadEndpointDefinitionsFromEmbeddedResource() and that method opens a stream to load some embedded resources which could throw the stream exception I think .. could this be invalid bundling for resources while building the xamarin iOS Unified api DLL ?

To reproduce just put this code on any Xamarin.iOS Unified API project :

AmazonS3Config config = new AmazonS3Config();
config.ServiceURL = "s3.amazonaws.com",
config.UseHttp = true,
// exception thrown on this line :
config.RegionEndpoint = Amazon.RegionEndpoint.EUWest1,

**Comment by mzekrallah** [comment]
tried them all .. the same exception ..

**Comment by tawalke** [comment]
I will have to try to reproduce, like I noted I have an Xamarin Unified iOS app that is running fine using the same assembly, and I set the Regional Endpoint on each call.  I will try to add your code to that sample to see if this error happens in order to reproduce.


TEW






Sent from Windows Mail





From: mzekrallah
Sent: ‎Monday‎, ‎February‎ ‎23‎, ‎2015 ‎10‎:‎23‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





tried them all .. the same exception ..

**Comment by mzekrallah** [comment]
Thank you Tara. To save your time, I bundled a sample project to reproduce the problem. You can find it here : https://www.dropbox.com/s/jdcq452la29q5ne/AmazonSDKIssues.rar?dl=0

**Comment by tawalke** [comment]
Thanks, I will download and try it.






Sent from Windows Mail





From: mzekrallah
Sent: ‎Monday‎, ‎February‎ ‎23‎, ‎2015 ‎10‎:‎51‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Thank you Tara. To save your time, I bundled a sample project to reproduce the problem. You can find it here : https://www.dropbox.com/s/jdcq452la29q5ne/AmazonSDKIssues.rar?dl=0

**Comment by mzekrallah** [comment]
Hi Tara, any luck figuring the cause of the problem ?

**Comment by tawalke** [comment]
No, I am not getting the error.  I’m going to try and leverage my other machine to try an recreate your issue.   But it is returning an RegionEndpoint successfully for me.


Just to recap and ensure we are on the same page, you added the AWS_Mobile.dll to the references of your project from the Compiled_Binaries folder, from the iOS folder (not iOS Classic).    Your project say the AWS Services therein, but when you attempted to do an S3 Transfer it failed with a NullException when calling function of RegionEndpoint.  Are these the steps you took?  











Sent from Windows Mail





From: mzekrallah
Sent: ‎Wednesday‎, ‎February‎ ‎25‎, ‎2015 ‎1‎:‎56‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Hi Tara, any luck figuring the cause of the problem ?

**Comment by mzekrallah** [comment]
Hi Tara. Yes, like you said but no need to reach the s3 stuff .. it breaks immediately setting config.RegionEndPoint.. execution doesn't even reach the s3 code.

Exact Repro Steps :
- Create Unified iOS Project.
- Add "AWSSDK_XMOBILE.dll" reference from "Compiled_Binaries_Assemblies/iOS Unified API".
- Add These Lines in ViewDidLoad in any new controller :

AmazonS3Config config = new AmazonS3Config();
config.ServiceURL = "s3.amazonaws.com";
config.UseHttp = true;
// exception is thrown in this line
config.RegionEndpoint = RegionEndpoint.USEast1;

Result : ArgumentNullException : stream cannot be null thrown immediately when code execution reaches the above line for setting the RegionEndPoint.

Note : I just pulled the dll again today and the same issue persist.

Please Help.

**Comment by tawalke** [comment]
Those are the steps I followed. I will continue to try to reproduce.

Sent from my Windows Phone
________________________________

**Comment by tawalke** [comment]
Just curious, if you start a iOS Classic project and leverage this same code do you have the issue?  I have a theory, the Classic and Unified have the same code base but are leveraging different libraries.  Please advise. 






Sent from Windows Mail





From: mzekrallah
Sent: ‎Thursday‎, ‎February‎ ‎26‎, ‎2015 ‎1‎:‎24‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Hi Tara. Yes, like you said but no need to reach the s3 stuff .. it breaks immediately setting config.RegionEndPoint.. execution doesn't even reach the s3 code.

Exact Repro Steps :
Create Unified iOS Project.
Add "AWSSDK_XMOBILE.dll" reference from "Compiled_Binaries_Assemblies/iOS Unified API".
Add These Lines in ViewDidLoad in any new controller :

AmazonS3Config config = new AmazonS3Config();
config.ServiceURL = "s3.amazonaws.com";
config.UseHttp = true;
// exception is thrown in this line
config.RegionEndpoint = RegionEndpoint.USEast1;

Result : ArgumentNullException : stream cannot be null thrown immediately when code execution reaches the above line for setting the RegionEndPoint.

Note : I just pulled the dll again today and the same issue persist.

Please Help.

**Comment by mzekrallah** [comment]
Tara, I just tried your suggestion and created a classic API project using the same code above  .. Now, not only the RegionEndPoint problem is solved .. the s3 code worked and the file is even uploaded to S3 successfully !!

 So, it's definitely related to the Unified API version of the amazon sdk dll... Plz help

**Comment by tawalke** [comment]
Excellent news. So the problem is centralized to the Unified Migrated API!  That helps me so much, I guessed as much migration has been interesting.  


I will research. 


Thanks,

TEW  






Sent from Windows Mail





From: mzekrallah
Sent: ‎Saturday‎, ‎February‎ ‎28‎, ‎2015 ‎11‎:‎26‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Tara, I just tried your suggestion and created a classic API project using the same code above .. Now, not only the RegionEndPoint problem is solved .. the s3 code worked and the file is even uploaded to S3 successfully !!

So, it's definitely related to the Unified API version of the amazon sdk dll... Plz help

**Comment by mzekrallah** [comment]
Tara, I solved it. Unfortunately, it seems the dll put in the Compiled Unified API folder is not the same as the one that gets built from the source code. they are not even the same size !! I just built the dll in debug and release mode from the source code and used it in a unified project and it worked !

**Comment by tawalke** [comment]
Yay!!! Excellent news, I could not get it to error for me.  I will replace the assembly in the Unified folder.

Sent from my Windows Phone
________________________________

**Comment by dmennis** [comment]
I reproduced mzekrallah's issue using the sample S3 config code provided and came up with the same conclusion. If I download the AWSSDK_XMOBILE.dll from "Compiled Binaries_Assemblies" here: https://github.com/awslabs/aws-sdk-xamarin/tree/master/Compiled%20Binaries_Assemblies/iOS%20Unified%20API I get the same error. I also got the same error when deleting this reference and installed the latest from Nuget. The solution for now (until Tara fixes the binary) is to download the entire source, compile, and then copy the AWSSDK_XMOBILE.dll from AWSSDK_iOS/bin/Release into your project. Here's my environment:
Macbook Pro
Xamarin Studio
New Solution: iOS Unified API Universal Single View Application

**Comment by mzekrallah** [comment]
Thanks dmennis, yes we totally need a fix for replaced dll in compiled folder for now + proper nuget package support (eventually).

**Comment by tawalke** [comment]
Thanks guys.

No worries, I will replace the dll on tomorrow (or today now).  But good to know it is simply a file placement issue and not the code that has an issue. This explains why I wasn't getting the problem.  Additionally, I may remove the Unified DLL from the Nuget package until support is more native for the new iOS API.

Sent from my Windows Phone
________________________________

**Comment by theofanis** [comment]
I still get the same error when adding the package from nuget. Is nuget still providing the "broken" dll?

**Comment by tawalke** [comment]
Yes, please compile from repo.

Sent from my Windows Phone
________________________________

**Comment by theofanis** [comment]
That's what I did, and it works, I just thought of posting it here, since your previous comment said that you would update the dll in the compiled binaries folder, but unfortunately it appears this isn't the case.

Thanks.

**Comment by tawalke** [comment]
No not as yet, it is important that the correct folders are supported.  With the release of v4 on next week, new NuGet packages will be created. 


-TEW






Sent from Windows Mail





From: Theofanis Tokas
Sent: ‎Sunday‎, ‎April‎ ‎19‎, ‎2015 ‎3‎:‎53‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





That's what I did, and it works, I just thought of posting it here, since your previous comment said that you would update the dll in the compiled binaries folder, but unfortunately it appears this isn't the case.

Thanks.

**Comment by theofanis** [comment]
Great to hear a new version is so close. Bring it on!

**Comment by tawalke** [comment]
This was resolved in v3 of the SDK.
