### ISSUE TITLE
DynamoDB

### ISSUE THREAD

**Issue by jbarreda** [awslabs/aws-sdk-xamarin#15]
I am trying to get an item back from the data we uploaded, but get the error:
"The provided key element does not match the schema"

I am following the sample found at:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDotNetQuery.html

I am querying on the Hash Key which is a string.  I also have a Range key on the table which is also a string but not doing anything with it and don't know if I need to.

Thanks!

**Comment by tawalke** [comment]
Hi @jbarreda: 

1.) First try to running your code with V3 of the SDK that just release 2 days ago to se if this fixes your issue. 
2.) The best place to ensure you are looking at the latest documentation and examples for DynamoDB is the AWS .NET Blog: http://blogs.aws.amazon.com/net/post/Tx2XQOCY08QMTKO/-span-class-matches-DynamoDB-span-Series-Kickoff

Let me know if you still have issues and you can share your code.
