### ISSUE TITLE
Nuget Package Installation Problem

### ISSUE THREAD

**Issue by mzekrallah** [awslabs/aws-sdk-xamarin#16]
I'm using Xamarin Studio 5.7.1 on a Xamarin.iOS Unified API project and after installing this SDK from Nuget Package, I get 3 compilation errors :

- Error CS1703: An assembly `System.IO' with the same identity has already been imported. Consider removing one of the references (CS1703) 
- Error CS1703: An assembly `System.Runtime' with the same identity has already been imported. Consider removing one of the references (CS1703)
- Error CS1703: An assembly `System.Threading.Tasks' with the same identity has already been imported. Consider removing one of the references (CS1703)

Once I remove the duplicated assemblies references above, it compiles OK, however, I get a runtime exception in my iOS application immediately related to not being able to load the app main storyboard :

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Could not find a storyboard named 'MainStoryboard_iPhone' in bundle NSBundle ...

When I remove the package, everything start working back as usual with no problems and no more storyboard loading issues come up !

Please help ..

**Comment by tawalke** [comment]
Unfortunately, I have found that NuGet doesn’t have great automatic installation support for the new Xamarin.iOS (unified) project, therefore, it is installing the old iOS API for Xamarin when it detects Xamarin iOS.  The iOS Unified folder has been put in NuGet (Xamarin.iOS) but it doesn’t seem to be detecting the difference in this one and the Monotouch folder.  




As an interim workaround solution to this, I have added a folder to the Github repo that contains all of the precompiled binaries for the project.  You would simply need to go to the folder for the OS you are working on; in this case the folder, iOS Unified, under Compiled Binaries_Assemblies.  You would grab the assembly(ies) from the folder and manually add these as a reference to the project by going into Add Reference in your IDE and browsing to the location where you have downloaded the binaries.  


The link to the aforementioned folder is here: https://github.com/awslabs/aws-sdk-xamarin/tree/master/Compiled%20Binaries_Assemblies 


Thanks,

TEW




Sent from Windows Mail





From: mzekrallah
Sent: ‎Friday‎, ‎February‎ ‎20‎, ‎2015 ‎10‎:‎36‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'





I'm using Xamarin Studio 5.7.1 on a Xamarin.iOS Unified API project and after installing this SDK from Nuget Package, I get 3 compilation errors :
Error CS1703: An assembly `System.IO' with the same identity has already been imported. Consider removing one of the references (CS1703) 
Error CS1703: An assembly `System.Runtime' with the same identity has already been imported. Consider removing one of the references (CS1703)
Error CS1703: An assembly `System.Threading.Tasks' with the same identity has already been imported. Consider removing one of the references (CS1703)

Once I remove the duplicated assemblies references above, it compiles OK, however, I get a runtime exception in my iOS application immediately :

Objective-C exception thrown. Name: NSInvalidArgumentException Reason: Could not find a storyboard named 'MainStoryboard_iPhone' in bundle NSBundle ...

When I remove the package, everything start working back as usual with no problems !

Please help ..

**Comment by mzekrallah** [comment]
Thank you Tera for your prompt feedback ! 

Ok, I will try the manual assemblies .. However, I have seen other nuget packages working seamlessly with new iOS Unified Projects and picking up the right assemblies .. maybe it's an issue in nuget package publishing .. See this from Xamarin website, it could help :

NuGet packages that previously supported Xamarin.iOS via the Classic API published their assemblies using the Monotouch10 platform moniker.

The Unified API introduces a new platform identifier for compatible packages - Xamarin.iOS10. Existing NuGet packages will need to be updated to add support for this platform, by building against the Unified API.

http://developer.xamarin.com/guides/cross-platform/macios/unified/

Best Regards

**Comment by tawalke** [comment]
Hi: 


Let me know how the manual assemblies work for you.  The Xamarin.iOS10 folder is there and available for the AWS SDK for Xamarin nuget package, however, when installing via the IDE, it continues to install the Monotouch platform.  Not sure why this is the case, but the package will be rebuilt once another release is ready. 


Keep me posted if the manual fix is sufficient. 


Thanks,

TEW






Sent from Windows Mail





From: mzekrallah
Sent: ‎Friday‎, ‎February‎ ‎20‎, ‎2015 ‎12‎:‎23‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Thank you Tera for your prompt feedback ! 

Ok, I will try the manual assemblies .. However, I have seen other nuget packages working seamlessly with new iOS Unified Projects and picking up the right assemblies .. maybe it's an issue in nuget package publishing .. See this from Xamarin website, it could help :

NuGet packages that previously supported Xamarin.iOS via the Classic API published their assemblies using the Monotouch10 platform moniker.

The Unified API introduces a new platform identifier for compatible packages - Xamarin.iOS10. Existing NuGet packages will need to be updated to add support for this platform, by building against the Unified API.

http://developer.xamarin.com/guides/cross-platform/macios/unified/

Best Regards

**Comment by mzekrallah** [comment]
Yes, manual iOS Unified API assemblies worked for me. Thanks
