### ISSUE TITLE
CognitoCreds.GetCredentials() - Facebook login - Generating temporary creds works on Android Emulator but not Xamarin Android Player

### ISSUE THREAD

**Issue by jasonmc86** [awslabs/aws-sdk-xamarin#22]
Hey

Seems the credientials get stored locally on the device or something and expire?

Code:
CognitoCreds.AddLogin(provider, token);
TempCreds = CognitoCreds.GetCredentials();

What am i doing wrong to get the below.

Unhandled Exception:
04-09 21:26:27.497 E/mono    ( 1355): Amazon.Runtime.AmazonClientException: The retrieved credentials have already expired
04-09 21:26:27.497 E/mono    ( 1355):   at Amazon.Runtime.RefreshingAWSCredentials.UpdateToGeneratedCredentials (Amazon.Runtime.CredentialsRefreshState state) [0x00000] in <filename unknown>:0 
04-09 21:26:27.497 E/mono    ( 1355):   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentials () [0x00000] in <filename unknown>:0

**Comment by jasonmc86** [comment]
Note this is only on emulators inside Xamarin Android Player. 

The Android Emulator's work fine.

**Comment by frankmuellr** [comment]
Hello @jasonmc86,

Sorry for the delay. Do you still require help with this issue?
