### ISSUE TITLE
Update: Xamarin Forms SNS Docs For Android O/P

### ISSUE THREAD

**Issue by JoshuaNovak919** [awslabs/aws-sdk-xamarin#24]
Are there any docs for how to setup and use this plugin for Amazon SNS with Xamarin Forms?

**Comment by tawalke** [comment]
@JoshuaNovak919 Setup on Amazon SNS or code example of Xamarin Forms calling Amazon SNS?

**Comment by JoshuaNovak919** [comment]
Xamarin Forms calling Amazon SNS, but I managed to get some sample code now.

**Comment by codebase2015** [comment]
Hi Joushua
Could you please share the Amazon SNS from Xamarin Forms example it would be great help.
Thank you
Ashish

**Comment by poodle989** [comment]
Is there any chance we can get some updated docs/examples? With recent changes made to android O the current example will cause the app to crash.

**Comment by frankmuellr** [comment]
I ported this issue to the main Xamarin repo: https://github.com/aws/aws-sdk-net/issues/1113
