### ISSUE TITLE
Update Nuget Package

### ISSUE THREAD

**Issue by JoshuaNovak919** [awslabs/aws-sdk-xamarin#25]
The version has changed here, but the Nuget package is still version 2.1.7

**Comment by tawalke** [comment]
It will be updated as well.  Testing to ensure iOS64 nugget download issue is resolved.






Sent from Windows Mail





From: JoshuaNovak919
Sent: ‎Wednesday‎, ‎April‎ ‎29‎, ‎2015 ‎3‎:‎56‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'





The version has changed here, but the Nuget package is still version 2.1.7

**Comment by JoshuaNovak919** [comment]
Ok, awesome! Thanks!
