### ISSUE TITLE
v4 doesn't compile giving 49 errors

### ISSUE THREAD

**Issue by theofanis** [awslabs/aws-sdk-xamarin#26]
Any update on when we're going to have a nuget update for v4?

We're still getting null exception for region endpoint as discussed elsewhere with the already compiled dll.

Trying to build for iOS, we get 49 errors...

```
Build FAILED.
Errors:

/Users/hampos/Downloads/aws-sdk-xamarin-master-3/AWS.XamarinSDK/AWSSDK_iOS/AWSSDK_iOS.csproj (Build) ->
/Library/Frameworks/Mono.framework/Versions/4.0.0/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Credentials.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Credentials.Extensions.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/DescribeIdentityRequest.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/DescribeIdentityResponse.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/DescribeIdentityResult.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/GetCredentialsForIdentityRequest.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/GetCredentialsForIdentityResponse.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/GetCredentialsForIdentityResult.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/GetIdentityPoolRolesRequest.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/GetIdentityPoolRolesResponse.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/GetIdentityPoolRolesResult.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/CredentialsUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/DescribeIdentityRequestMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/DescribeIdentityResponseUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/GetCredentialsForIdentityRequestMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/GetCredentialsForIdentityResponseUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/GetIdentityPoolRolesRequestMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/GetIdentityPoolRolesResponseUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/SetIdentityPoolRolesRequestMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/Internal/MarshallTransformations/SetIdentityPoolRolesResponseUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/InvalidIdentityPoolConfigurationException.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/SetIdentityPoolRolesRequest.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoIdentity/Model/SetIdentityPoolRolesResponse.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/AlreadyStreamedException.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/BulkPublishRequest.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/BulkPublishResponse.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/BulkPublishResult.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/CognitoStreams.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/DuplicateRequestException.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/GetBulkPublishDetailsRequest.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/GetBulkPublishDetailsResponse.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/GetBulkPublishDetailsResult.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/BulkPublishRequestMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/BulkPublishResponseUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/CognitoStreamsMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/CognitoStreamsUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/GetBulkPublishDetailsRequestMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/GetBulkPublishDetailsResponseUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/KinesisStreamingMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/Internal/MarshallTransformations/KinesisStreamingUnmarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.CognitoSync/Model/KinesisStreaming.cs' could not be found
	CSC: error CS2001: Source file `Amazon.DynamoDBv2/DataModel/Context_45.cs' could not be found
	CSC: error CS2001: Source file `Amazon.DynamoDBv2/Model/CreateGlobalSecondaryIndexAction.cs' could not be found
	CSC: error CS2001: Source file `Amazon.DynamoDBv2/Model/DeleteGlobalSecondaryIndexAction.cs' could not be found
	CSC: error CS2001: Source file `Amazon.DynamoDBv2/Model/Internal/MarshallTransformations/CreateGlobalSecondaryIndexActionMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.DynamoDBv2/Model/Internal/MarshallTransformations/DeleteGlobalSecondaryIndexActionMarshaller.cs' could not be found
	CSC: error CS2001: Source file `Amazon.Lambda/Model/UploadFunctionRequest.Extensions.cs' could not be found
	CSC: error CS2001: Source file `Amazon.Runtime/Internal/Util/Collections.cs' could not be found
	CSC: error CS2001: Source file `Amazon.Runtime/RequestMetrics.cs' could not be found

	 0 Warning(s)
	 49 Error(s)
```

**Comment by tawalke** [comment]
Are you building with Compiler directives from Debug?

Sent from my Windows Phone
________________________________

**Comment by theofanis** [comment]
If you mean if current configuration when building is `Debug`, then yes.

**Comment by tawalke** [comment]
Hi: 

I meant to see






Sent from Windows Mail





From: Theofanis Tokas
Sent: ‎Sunday‎, ‎May‎ ‎3‎, ‎2015 ‎5‎:‎30‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





If you mean if current configuration when building is Debug, then yes.

**Comment by tawalke** [comment]
I meant if the compiler directives were there when you were compiling the project, or if this is showing files missing which would be odd given they are available in the repository.  I would suggest doing a git pull to ensure all the files have come down.  Please advise afterwards if you are still getting compilation errors so further investigation or another push to the repository can be made as all projects do successful compile. 


-TEW






Sent from Windows Mail





From: Theofanis Tokas
Sent: ‎Sunday‎, ‎May‎ ‎3‎, ‎2015 ‎5‎:‎30‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





If you mean if current configuration when building is Debug, then yes.

**Comment by theofanis** [comment]
I'm sorry but I can't test this out now, since we moved to a Xamarin.Mac 2.0 project targeting .NET 4.5, so we're using AWS SDK for .NET without problems. If we come back to Unified API, I'll test it out and report back.

Thanks.

**Comment by tawalke** [comment]
No worries, the NuGet package testing should be complete by end of this week.  Additionally, the tested Compiled Binaries folder containing v4 binaries will be updated this week as well.  You will then be able to run a Unified API project without compilation.  I will put instructions for compilation on GitHub in case you still need to compile and have issues.


-TEW





Sent from Windows Mail





From: Theofanis Tokas
Sent: ‎Monday‎, ‎May‎ ‎4‎, ‎2015 ‎5‎:‎14‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





I'm sorry but I can't test this out now, since we moved to a Xamarin.Mac 2.0 project targeting .NET 4.5, so we're using AWS SDK for .NET without problems. If we come back to Unified API, I'll test it out and report back.

Thanks.

**Comment by luispedrofonseca** [comment]
I'm getting this problem too and I need V4 asap due to this problem: https://github.com/awslabs/aws-sdk-xamarin/issues/23

Is there any quick-fix or any way to get access to the new compiled DLL's sooner?

**Comment by tawalke** [comment]
Hi Luis: 


Three things: 

1.) Your error is resolved with compiling the project vs. using the NuGet package, therefore, previous branch is available on github as well to fix this asap. 


2.) Did you do a git pull on the project and the files noted in the error file are not coming down and did you compile with the compiler directives which has been the reason most people fail in compile when switching to release?  I will review this and investigate why the files are not coming down, but please advise regarding the two questions.. 



3.) Yes, I will work on updating the compiled DLLs and post earlier as soon as it is possible to do so, even if this is just for Unified iOS making the completion of this test a priority. 


Sent from Windows Mail





From: Luis Fonseca
Sent: ‎Monday‎, ‎May‎ ‎4‎, ‎2015 ‎5‎:‎43‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





I'm getting this problem too and I need V4 asap due to this problem: #23

Is there any quick-fix or any way to get access to the new compiled DLL's sooner?

**Comment by luispedrofonseca** [comment]
Thanks mate! Recompiling the previous branch solved it for me! ;)

**Comment by tawalke** [comment]
Missing files causing compilation issues were updated and this should be resolved for all branches
