### ISSUE TITLE
StreamTransferProgress firing rapidly when upload starts until progress reaches the file size.

### ISSUE THREAD

**Issue by theofanis** [awslabs/aws-sdk-xamarin#27]
I can't replicate this now and report something more organized, but before switching out to Xamarin.Mac 2.0 targeting .NET 4.5 instead of Mobile Unified API, I got rapid successive progress updates from StreamTransferProgress event, which stopped when progress equaled the file size, but the upload was still ongoing.

My upload speeds at the moment were about 100 KB/s, and I reported progress every 200 KB (ProgressUpdateInterval was set to 2097152 bytes), so seeing immediate successive progress reports for a 1 MB file right after starting the upload is definitely not regular.

Buffer size was the default 8192, but this behavior really looked like reporting progress of buffering a stream in memory and not of actual transferred bytes progress, it reported that fast.

Just opening an issue for you here @tawalke, so you can investigate this.

**Comment by tawalke** [comment]
@theofanis : This is using the AWS .NET SDK or AWS.Xamarin SDK?  Wanted to verify I believe this is from NET 4.5 SDK correct?  Also can you give me more details ...so immediately you get progress reports and it is reporting what data 200KB or more, 200KB or less, or something totally different?

**Comment by tawalke** [comment]
Hi:

This Beta SDK should now be migrated to use the AWS SDK for .NET with  Xamarin has been released.  As noted, this release is under AWS SDK for .NET and is in Developer Preview.  The Xamarin SDK repo has the latest links for this update, as well as, the updates for the updated NuGet packages.

This should resolve you issue as this has the updated services and codebase desired.  See links below: 
https://github.com/aws/aws-sdk-net
https://github.com/aws/aws-sdk-net#nuget-packages
