### ISSUE TITLE
S3 Client Error - Argument cannot be null. Parameter name: stream

### ISSUE THREAD

**Issue by mgamache** [awslabs/aws-sdk-xamarin#28]
Trying to create an S3 client results in the following error:
*Argument cannot be null.
Parameter name: stream*

```var client =new AmazonS3Client(
				"xxxx",
				"xxxx",Amazon.RegionEndpoint.USEast1
			);```

Xamrin ios Version: 8.10.0.267

**Comment by tawalke** [comment]
@mgamache Is this the iOS Unified?  How did you install it? via NuGet, Compiled Binaries , or Compilation of Library

**Comment by mgamache** [comment]
iOS Unified

I installed via NuGet and when that failed I tried Compiling the Binaries from the source.

**Comment by tawalke** [comment]
Compiling the binaries from source should solve the problem.  The AWSSDK_iOS is for Unified API (64bit) and AWSSDK_iOS-Classic is for the previous iOS development (32bit). 


What happened when you compiled from source?  I’m assuming you are using Xamarin Studio, so make sure when you switch from Debug to Release that the compilation directives are there.








Sent from Windows Mail





From: mgamache
Sent: ‎Wednesday‎, ‎May‎ ‎20‎, ‎2015 ‎9‎:‎05‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: tawalke





iOS Unified

I installed via NuGet and when that failed I tried Compiling the Binaries from the source.

**Comment by mgamache** [comment]
I got the same result compiling from the source using Unified / Release build (pulled the dll from the release directory with a correct timestamp). maybe I'm doing something wrong I'll check again.

**Comment by mgamache** [comment]
I cloned the project again. Of course I had to remove the readme file to get it to build, but it didn't prevent the error.

**Comment by mgamache** [comment]
OK! I see that the endpoints.xml was not set correctly in the Unified iOS project. It was set only to *content  not embedded resource*. I made that change and now it seems to let me create a client.

**Comment by tawalke** [comment]
Odd, that should not be set to content in the project.  The original project file I just checked and it has it set. I will push another .sln to ensure accuracy. Thanks so much for this feedback.

Sent from my Windows Phone
________________________________

**Comment by tawalke** [comment]
@mgamache I just updated on the repository ensuring the endpoint.xml is set corrected in the iOS Unified project.  Additionally updated the iOS Unified assembly in the Compiled Binaries.  Thanks again for your feedback.
