### ISSUE TITLE
Does aws-sdk-xamarin have dynamodb mapper

### ISSUE THREAD

**Issue by jasonmc86** [awslabs/aws-sdk-xamarin#29]
Hey @tawalke, does this library (aws-sdk-xamarin) have the concept of a dynamodb mapper or an alternative?

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html?

Cheers,

Jason

**Comment by tawalke** [comment]
@jasonmc86 Not quite but you should be able to use the Document API: http://blogs.aws.amazon.com/net/post/Tx2R0WG46GQI1JI/-span-class-matches-DynamoDB-span-Series-Document-Model

**Comment by tawalke** [comment]
Let me know if this provides what you want with JSON.NET serializing to an object and back out.

**Comment by findly-jasonmcmonagle** [comment]
Yep document api and newtonsoft worked together perfectly to give me what i needed thanks :+1:

**Comment by tawalke** [comment]
Excellent, glad to hear it!
