### ISSUE TITLE
Cognito Sync Credientials not right sometimes

### ISSUE THREAD

**Issue by jasonmc86** [awslabs/aws-sdk-xamarin#32]
Hey, 

I sometimes get this error when i'm trying todo mutliple async client calls with aws-sdk-xamarin cognito sync. Sometimes it just works fine...

Seems its something to do with multiple threads but not 100% sure.

 UNHANDLED EXCEPTION:
[MonoDroid] Amazon.CognitoSync.AmazonCognitoSyncException: Signature expired: 20150520T094646Z is now earlier than 20150526T080638Z (20150526T081138Z - 5 min.) ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
[MonoDroid]   at Amazon.Runtime.HttpWebRequestMessage+<GetResponseAsync>d__0.MoveNext () [0x00140] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\HttpHandler\HttpRequestMessageFactory.cs:230 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Amazon.Runtime.Internal.Transform.IWebResponseData].GetResult () [0x00000] in <filename unknown>:0 
[MonoDroid]   at Amazon.Runtime.Internal.HttpHandler`1+<InvokeAsync>d__0`1[System.Net.Http.HttpContent,Amazon.CognitoSync.Model.ListRecordsResponse].MoveNext () [0x0028f] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:159 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Amazon.CognitoSync.Model.ListRecordsResponse].GetResult () [0x00000] in <filename unknown>:0 
[MonoDroid]   at Amazon.Runtime.Internal.Unmarshaller+<InvokeAsync>d__0`1[Amazon.CognitoSync.Model.ListRecordsResponse].MoveNext () [0x0001e] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:67 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <filename unknown>:0 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Amazon.CognitoSync.Model.ListRecordsResponse].GetResult () [0x00000] in <filename unknown>:0 
[MonoDroid]   at Amazon.Runtime.Internal.ErrorHandler+<InvokeAsync>d__1`1[Amazon.CognitoSync.Model.ListRecordsResponse].MoveNext () [0x00035] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:97 
[MonoDroid]   --- End of inner exception stack trace ---
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00078>
[MonoDroid] at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) <IL 0x00006, 0x0006b>
[MonoDroid] at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/platforms/android-15/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.0eea6552-0dec-4b84-8f84-265435d90443 (intptr,intptr) <IL 0x00011, 0x0004b>
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
[AndroidRuntime] Shutting down VM

Cheers,

Jason

**Comment by tawalke** [comment]
Any pattern that you can glean from when the exception occurs?






Sent from Windows Mail





From: Jason McMonagle
Sent: ‎Tuesday‎, ‎May‎ ‎26‎, ‎2015 ‎4‎:‎14‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'





Hey, 

I sometimes get this error when i'm trying todo mutliple async client calls with aws-sdk-xamarin cognito sync. Sometimes it just works fine...

Seems its something to do with multiple threads but not 100% sure.

UNHANDLED EXCEPTION:
[MonoDroid] Amazon.CognitoSync.AmazonCognitoSyncException: Signature expired: 20150520T094646Z is now earlier than 20150526T080638Z (20150526T081138Z - 5 min.) ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
[MonoDroid] at Amazon.Runtime.HttpWebRequestMessage+d__0.MoveNext () [0x00140] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\HttpHandler\HttpRequestMessageFactory.cs:230 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in :0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in :0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in :0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in :0 
[MonoDroid] at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[Amazon.Runtime.Internal.Transform.IWebResponseData].GetResult () [0x00000] in <filename unknown>:0 
[MonoDroid] at Amazon.Runtime.Internal.HttpHandler1+d__01[System.Net.Http.HttpContent,Amazon.CognitoSync.Model.ListRecordsResponse].MoveNext () [0x0028f] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:159 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[Amazon.CognitoSync.Model.ListRecordsResponse].GetResult () [0x00000] in :0 
[MonoDroid] at Amazon.Runtime.Internal.Unmarshaller+d__01[Amazon.CognitoSync.Model.ListRecordsResponse].MoveNext () [0x0001e] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:67 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <filename unknown>:0 
[MonoDroid] at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter[Amazon.CognitoSync.Model.ListRecordsResponse].GetResult () [0x00000] in :0 
[MonoDroid] at Amazon.Runtime.Internal.ErrorHandler+d__1`1[Amazon.CognitoSync.Model.ListRecordsResponse].MoveNext () [0x00035] in c:\Users\JASONMC\Downloads\aws-sdk-xamarin-master\aws-sdk-xamarin-master\AWS.XamarinSDK\AWSSDK_Android\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:97 
[MonoDroid] --- End of inner exception stack trace ---
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () 
[MonoDroid] at System.Runtime.CompilerServices.AsyncMethodBuilderCore.m__0 (object) 
[MonoDroid] at Android.App.SyncContext/c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/platforms/android-15/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.0eea6552-0dec-4b84-8f84-265435d90443 (intptr,intptr) 
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable
[AndroidRuntime] Shutting down VM

Cheers,

Jason

**Comment by jasonmc86** [comment]
@tawalke worked it out, i had the clock on my test phone not set at the current date/time and therefore i think the library was checking the wrong date/time. Interesting bug tho

**Comment by tawalke** [comment]
I am glad you were able to reproduce.  I was trying to make the bug happen on my end.  The time is checked for calls.  If you look in our documentation you will note this.  I will post the link in for review if desired.

Sent from my Windows Phone
________________________________

**Comment by tawalke** [comment]
Hi:

This Beta SDK should now be migrated to use the AWS SDK for .NET with  Xamarin has been released.  As noted, this release is under AWS SDK for .NET and is in Developer Preview.  The Xamarin SDK repo has the latest links for this update, as well as, the updates for the updated NuGet packages.

This should resolve you issue as this has the updated services and codebase desired.  See links below: 
https://github.com/aws/aws-sdk-net
https://github.com/aws/aws-sdk-net#nuget-packages
