### ISSUE TITLE
Invoking lambda function

### ISSUE THREAD

**Issue by ceichin** [awslabs/aws-sdk-xamarin#34]
Hi,
I'm trying to invoke a lambda function:
```
try 
{
    AmazonLambdaClient lambdaClient = new AmazonLambdaClient("7826", "8326", 
        RegionEndpoint.USEast1);

    InvokeAsyncRequest ir = new InvokeAsyncRequest() {
        FunctionName = "arn:aws:lambda:us-east-1:772937:function:Blah",
        InvokeArgs = @"{""username"": ""john"", ""password"": ""pass""}"
    };

    InvokeAsyncResponse resp = await lambdaClient.InvokeAsyncAsync(ir);

    Console.WriteLine("Status code: " + resp.Status);
    Console.WriteLine("Response: " + resp.??????); // where can I get the response body?????
}
catch (Exception ex) 
{
    Console.WriteLine("error: " + ex.Message);
}
```

I receive a 202 status code and the function runs perfectly, but I don't know how to get the response.

Is it doing an asynchronous invocation and that's why I can't see the response? (lambdaClient.InvokeAsyncAsync(ir))

More docs please !! 
Thanks!

**Comment by tawalke** [comment]
@ceichin:
InvokeAsync(InvokeAsyncResponse) is deprecated.  Use InvokeAsync( InvokeRequest request,
         CancellationToken cancellationToken) which will  return Task<InvokeResponse>.  InvokeResponse has a Payload property which will have the JSON result of the Lambda call.  See API info in links below: 
http://docs.aws.amazon.com/sdkfornet/latest/apidocs/items/MLambda_LambdaInvokeAsync_InvokeRequest_CancellationTokenNET4_5.html 
http://docs.aws.amazon.com/sdkfornet/latest/apidocs/items/TLambdaInvokeResponse_NET4_5.html

**Comment by ceichin** [comment]
Thank your for your response. 

I can't access that method from the lambda client. I checked in the lambda client class and didn't find the method you said neither, there is an InvokeAsync that is internal and then AmazonLambdaClient.Extension.cs has public InvokeAsync methods but I can't access them (maybe because there is a #if BCL? Idk).

I Hope you can help me to figure this out!

**Comment by tawalke** [comment]
No worries, let me see what is going on.  I'll write a test.  Give me a day to research a solution, I am traveling today but will look at this tonight.

Sent from my Windows Phone
________________________________

**Comment by ceichin** [comment]
Thank you, no hurries!

**Comment by ceichin** [comment]
Any news on this?

**Comment by tawalke** [comment]
Yes, trying to understand why you are not sending the other object.  Give me a few more days of research please.






Sent from Windows Mail





From: ceichin
Sent: ‎Monday‎, ‎July‎ ‎6‎, ‎2015 ‎3‎:‎59‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: tawalke





Any news on this?

**Comment by ceichin** [comment]
Here is exactly what I did so it's easier for you to review and recreate:

1. Xamarin Studio on Mac - new iOS app empty project
2. Copy file from Github in the project: Compiled Binaries_Assemblies/iOS Unified API/AWSSDK_XMOBILE.dll
3. Add the Assembly Reference to the project
4. Add this method to AppDelegate.cs:

```
async void AWSLambda()
{
    try 
    {
        AmazonLambdaClient lambdaClient = new AmazonLambdaClient("XXX", "XXX",
            RegionEndpoint.USEast1);

        var ir = new InvokeAsyncRequest() {
            FunctionName = "arn:aws:lambda:us-east-1:XXXX:function:Signup",
            InvokeArgs = @"{""username"": ""john"", ""password"": ""pass""}"
        };

        InvokeAsyncResponse resp = await lambdaClient.InvokeAsyncAsync(ir);

        Console.WriteLine("Status code: " + resp.Status);
    }
    catch (Exception ex) 
    {
        Console.WriteLine("error: " + ex.Message);
    }
}
```

5 . Resolve the issues adding the respective usings and call it asynchronously from FinishedLaunching
6 . Run the app in the simulator

This gets a 202 status code and successfully runs the function.

Now, the problem. I used InvokeAsyncAsync(...), but I need InvokeAsync(...) to get the payload, but when I write "lambdaClient." intellisense doesn't suggest me any InvokeAsync method nor compiles when I write that.

Maybe I'm not doing it as expected.

Thanks! Hope it helps.

**Comment by dmennis** [comment]
ceichin/twalke,

I just ran through this scenario and it's true that the latest unified build AWSSDK_XMOBILE.dll implementation of InvokeAsync DOES NOT return the Payload. This appears to be the expected behavior based on the Lambda API. The InvokeAsync API will only return the status and metadata (request Id). This is the same behavior in the latest .NET SDK as well. The only way to get the JSON representation of the object returned by the Lambda function (Payload) is to call the 'Invoke' API which is not available in this build. 

Invoke API:
http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

InvokeAsync API: 
http://docs.aws.amazon.com/lambda/latest/dg/API_InvokeAsync.html

Here's what the 'Invoke' call looks like from the latest AWS .NET SDK: http://pastebin.com/ahjfyWCN

**Comment by ceichin** [comment]
dmennis, thank you for your response.

I'm working on a project and we need to start to work in the service layer soon. So, I was wondering if the Lambda Invoke api (the one that returns the payload) will be available in the next build version, and how far in time will that approximately be. If not, I see the possibilities of using directly the http api (which I really hate cause all the signature stuff), I could try to find another xamarin binding of the ios aws sdk, or I can use another backend service with an sdk or easier api.

This official sdk is my first choice, but I need the payload. Thanks, I hope you can help us!

**Comment by tawalke** [comment]
We are working on an updated version of the SDK that will provide this functionality.  Do you have a set time this needs to be completed?

I can work on a quick update to expose this if you need it immediately. Please advise.

Sent from my Windows Phone
________________________________

**Comment by ceichin** [comment]
@tawalke: I guess the end of next week or the week of Monday 20th we are going to start to code for the backend. That would be ideal, if I have the api that returns a payload for then it would be really awesome.

**Comment by Exakramone** [comment]
Hello, I am wondering how would I use a rds database specifically postgresql for authentication for cognito sync

Sent by Outlook for Android





On Fri, Jul 10, 2015 at 2:54 PM -0700, "tawalke" <notifications@github.com> wrote:
We are working on an updated version of the SDK that will provide this functionality.  Do you have a set time this needs to be completed?

I can work on a quick update to expose this if you need it immediately. Please advise.

Sent from my Windows Phone
________________________________

**Comment by ceichin** [comment]
Should I expect this implementation for the next two days? Thanks.

**Comment by tawalke** [comment]
Hi: 


The Xamarin Developer Preview has been released.  This release is under AWS SDK for .NET and is in Developer Preview.  The Xamarin SDK repo has the latest links for this update, as well as, the updates for the updated NuGet packages.  


This should resolve you issue as this has the updated services and codebase desired.






Sent from Windows Mail





From: ceichin
Sent: ‎Tuesday‎, ‎July‎ ‎21‎, ‎2015 ‎9‎:‎15‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: tawalke





Should I expect this implementation for the next two days? Thanks.

**Comment by CliffCawley** [comment]
@tawalke Sorry to open this one up again, but I'm trying to get the payload/response and using the latest Lambda api (3.1.2.2), however all I have in AmazonLambdaClient are InvokeAsync and InvokeAsyncAsync (which is obsolete).

InvokeAsync returns metadata but I can't get any payload or response and the response content length is 0.

What call do I use to include the response data?
