### ISSUE TITLE
DynamoDB Issue is not authorized to perform: dynamodb:GetItem on resource

### ISSUE THREAD

**Issue by Madhesk** [awslabs/aws-sdk-xamarin#35]
DynamoDB not allowed the user for "SPECIFIC_ATTRIBUTES" only, but "ALL_ATTRIBUTES" is working fine.

Here is my policy:

{

"Version": "2012-10-17",

"Statement": [

{

"Effect": "Allow",

"Action": [

"dynamodb:GetItem",

"dynamodb:Query"
],

"Resource": [

"*"
],

"Condition": {

"ForAllValues:StringEquals": {

"dynamodb:LeadingKeys": [

"${graph.facebook.com:id}"

],

"dynamodb:Attributes": [

"UserId",

"FirstName",

"LastName"

]

},

"StringEqualsIfExists": {

"dynamodb:Select": "SPECIFIC_ATTRIBUTES",

"dynamodb:ReturnValues": [

"NONE",

"UPDATED_OLD",

"UPDATED_NEW"

]

}
}

}

]

}

**Comment by EmilAlipiev** [comment]
Try to add "dynamodb:describetable" and see if that helps

**Comment by tawalke** [comment]
The best way to generate and validate policies is to use the AWS Policy Generator: http://awspolicygen.s3.amazonaws.com/policygen.html and the AWS Policy Validator within the IAM Console.  Instructions for using are here: http://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_policy-validator.html

**Comment by frankmuellr** [comment]
Hello @Madhesk,

Sorry for the delay. Do you still require help with this issue?

**Comment by frankmuellr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-net if are still encountering problems.
