### ISSUE TITLE
Is this project still live?

### ISSUE THREAD

**Issue by acmayberry** [awslabs/aws-sdk-xamarin#37]
I notice there have been no updates for over a year.  Has the Xamarin SDK been abandoned by Amazon?

**Comment by karthiksaligrama** [comment]
The xamarin sdk is now part of the official aws sdk for net https://github.com/aws/aws-sdk-net

**Comment by EmilAlipiev** [comment]
Does it only Support ios and Android?  What about uwp and wp8.1?

**Comment by tawalke** [comment]
@EmilAlipiev The Xamarin SDK has migrated to the .NET SDK here which supports more platforms: https://github.com/aws/aws-sdk-net
