### ISSUE TITLE
AWS S3 3.3.0 - Xamarin and iOS link error

### ISSUE THREAD

**Issue by Magic73** [awslabs/aws-sdk-xamarin#38]
Environment: Visual Studio 2015 - Xamarin 4.2.0.719 - Xamarin.iOS 10.2.0.4 - Xcode 10.1
Previously I used the 3.1.11 version, and I hadn't any issue.
Yesterday I updated my nuget package to the 3.3.0 and now I can't compile anymore with linker behaviour "SDK assembly only".
I'm able to compile only if I set linker behaviour to "don't link".

This is the error:
Failed to resolve "System.Void Amazon.Runtime.Internal.Util.AESEncryptionPutObjectStream::.ctor(System.IO.Stream,System.Byte[],System.Byte[])" reference from "AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604"

It isn't a xamarin issue.

**Comment by tawalke** [comment]
@Magic73 This SDK has merged with the .NET SDK which now supports .NET implementations including Xamarin. You can find this SDK here  https://github.com/aws/aws-sdk-net and it has the latest services and enhancements.
