### ISSUE TITLE
NullReferenceException on async methods.

### ISSUE THREAD

**Issue by Airat1995** [awslabs/aws-sdk-xamarin#40]
Hello, I tried to launch sample Xamarin Android app, after updating packages Core, S3, CognitoIdentity and SecurityToken.
Every time when I tried to call async method I get NullReferenceException.
Packages versions: 
Core: 3.3.7
S3: 3.3.5.2
SecurityToken: 3.3.0.7
CognitoIdentity: 3.3.1

Did someone faced with this problem? Or know how to fix it?

**Comment by frankmuellr** [comment]
Hello @Airat1995,

Sorry for the delay. Do you still require help with this issue?

**Comment by Airat1995** [comment]
Hello, thank you for the answer, but for me the issue is outdated.

Kindest regards, Airat.

________________________________
