### ISSUE TITLE
aws-iot on Xamarin

### ISSUE THREAD

**Issue by rvsonar** [awslabs/aws-sdk-xamarin#41]
What is the correct way to consume aws-iot services on Xamarin.Android and Xamarin.iOS?

Is there separate  SDK for that?

**Comment by Harikrishnav21** [comment]
@rvsonar Is there any update on this topic?
I need to interact  AWS-IOT with Xamarin.Android,iOS app through MQTT.

**Comment by tawalke** [comment]
Guys;  This version of the SDK has been deprecated and merged into the AWS .NET SDK: github.com/aws/aws-sdk-net 

You should be able to find the libraries for the latest AWS Services including IoT in that repo

**Comment by Harikrishnav21** [comment]
@tawalke  The AWSSDK-IOT is based out of HTTP. I need MQTT enabled .Net library for AWS IOT. any thoughts on this.

**Comment by mbilalriaz** [comment]
Use AWS Cognito services.

**Comment by frankmuellr** [comment]
Hello @rvsonar and @Bilal94,

Sorry for the delay. Do you still require help with this issue?

**Comment by frankmuellr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-net if are still encountering problems.
