### ISSUE TITLE
How can I enable the logs of aws ?

### ISSUE THREAD

**Issue by ph76** [awslabs/aws-sdk-xamarin#42]
I'm looking for the way to enable the logs for AWS SDK because this code doesnt work for me : 

var loggingConfig = AWSConfigs.LoggingConfig;
loggingConfig.LogMetrics = true;
loggingConfig.LogResponses = ResponseLoggingOption.Always;
loggingConfig.LogMetricsFormat = LogMetricsFormatOption.JSON;
loggingConfig.LogTo = LoggingOptions.Console;

I would like to just log in the the console and at all the level; 
It seems with other languages we can do it : 
...
AWSLogger.defaultLogger().logLevel = .Verbose
...
 in swift for example.

is it because Xamarin is  cross-platform, so the SDK ? 

 [http://docs.aws.amazon.com/fr_fr/mobileanalytics/latest/ug/sdk-logging.html](http://docs.aws.amazon.com/fr_fr/mobileanalytics/latest/ug/sdk-logging.html) 
[http://docs.aws.amazon.com/en_en/mobile/sdkforxamarin/developerguide/setup.html#set-logging](http://docs.aws.amazon.com/en_en/mobile/sdkforxamarin/developerguide/setup.html#set-logging)

Did I miss something ?

**Comment by ilpoimigee** [comment]
I am having similar problem. My AWS Mobile Analytics does not update service and I try to put logging on to analyze problem. But I am not able to enable logging nor AWS Mobile Analytics at all. 

Please let me know if you found answer to this problem.

**Comment by frankmuellr** [comment]
Hello @ph76 and @ilpoimigee,

Sorry for the delay. Do you still require help with this issue?

**Comment by frankmuellr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-net if are still encountering problems.
