### ISSUE TITLE
Cannot determine protocol error when executing UpdateUserAttributesRequest of AmazonCognitoIdentityProviderClient

### ISSUE THREAD

**Issue by niraj-bpsoftware** [awslabs/aws-sdk-xamarin#45]
Hi,
I am trying to update a user attribute but getting following error in .NET SDK:
Cannot determine protocol
StackTrace:
/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Signer.cs Line 124

My Code:
Error is thrown for UpdateUserAttributesRequest call:

`var credentials = new CognitoAWSCredentials(
                    Settings.IdentityPoolId,
                    Settings.Region
                );
credentials.AddLogin(Settings.IdentityProvider, idToken);

using (var provider = new AmazonCognitoIdentityProviderClient(credentials, Settings.Region))
{
	var response1 = await provider.ListUsersAsync(new ListUsersRequest
	{
		UserPoolId = Settings.UserPoolId,
		Filter = $"username = \"{userName}\""
	});
	var user = response1.Users.FirstOrDefault();
	if (user != null)
	{
		AttributeType profileAttributeType = user.Attributes.Find(a => a.Name == "profile");
		if (profileAttributeType == null)
		{
			user.Attributes.Add(new AttributeType(){Name = "profile", Value = "test2"});
		}
		else
		{
			profileAttributeType.Value = profileAttributeType.Value + "," + "test2";
		}

		

		**var response = await provider.UpdateUserAttributesAsync(
			new UpdateUserAttributesRequest()
			{
				
				UserAttributes = new List<AttributeType>() {profileAttributeType},
				AccessToken = accessToken
			});**

		return response;
	}
}`

**Comment by frankmuellr** [comment]
Hello @niraj-bpsoftware,

Sorry for the delay. Do you still require help with this issue?

**Comment by nirajvbhatt** [comment]
Hi @muellerfr , Thx for getting back, m using dynamodb table instead of custom attribute so all good.
