### ISSUE TITLE
Support Amazon Mobile Analytics

### ISSUE THREAD

**Issue by ddobrev** [awslabs/aws-sdk-xamarin#6]
Enable http://docs.aws.amazon.com/mobile/sdkforios/developerguide/analytics.html and http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/analytics.html to be doable through C#.

**Comment by ddobrev** [comment]
Once again, a whole month with no new code. Let me ask again, is this project taken seriously or will I have to listen to marketing lies until one day this SDK is officially pronounced dead?

**Comment by Mudeem** [comment]
Thank you for writing to us and providing feedback. We have no plans for deprecating the Xamarin SDK. Based on the current feedback we have slightly de-prioritized adding new services in the Xamarin SDK. We expect to actively resume the work in a few months time.

**Comment by alekseevpg** [comment]
So, i suppose few months already passed. Do we have some progress here?

**Comment by ddobrev** [comment]
@alekseevpg let me tell you, this project has proven itself as completely useless and abandoned time and time again. Your best bet, I am afraid, is creating .NET wrappers yourself, which is, at least in the iOS case, unfortunately far from trivial.

**Comment by alekseevpg** [comment]
@ddobrev sad but true. Did you already tried to wrap it?

**Comment by ddobrev** [comment]
@alekseevpg I have successfully wrapped the Android SDK - if you want, I can ask my employer if I may share the binding with you. However, with the iOS SDK I haven't even tried because the .a file is 72 MB large, this is way too large.

**Comment by alekseevpg** [comment]
@ddobrev well, I don't have any needs in android sdk for now, but i think it would be great if you can share it with the world anyway :)

**Comment by tawalke** [comment]
We have released 3 versions of the Xamarin SDK and about to release the 4th.  This project has not been abandoned as @ddobrev has noted incorrectly.  Version 3 released support for both iOS 32 and 64 bit versions and added enhancements and additions of AWS Services.


The Mobile Analytics piece was being worked on with the Unity SDK first and then the Xamarin SDK.  Unity SDK was finished on last week opening up the addition to the Xamarin SDK.  


Version 4 of the Xamarin (1-3 are already released on GitHub) has been completed and discussions are being had about what best for customers on release of v4 or delaying for push of Mobile Analytics.








Sent from Windows Mail





From: Paul
Sent: ‎Monday‎, ‎March‎ ‎23‎, ‎2015 ‎5‎:‎05‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





So, i suppose few months already passed. Do we have some progress here?

**Comment by alxbog** [comment]
@tawalke, any news on Mobile Analytics support? This is the only SDK part that we need in our app.

**Comment by tawalke** [comment]
Hi Alexey: 


This is being worked on and reviewed.  The version 4 will be released next week without it, but it is being currently addressed for release.   It will be uploaded to GitHub upon completion and review.






Sent from Windows Mail





From: Alexey Bogdanov
Sent: ‎Saturday‎, ‎April‎ ‎18‎, ‎2015 ‎5‎:‎04‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





@tawalke, any news on Mobile Analytics support? This is the only SDK part that we need in our app.

**Comment by alxbog** [comment]
@tawalke Good to hear!

How lightweight would it be? Will it have dependencies on other parts of the SDK? I think using Mobile Analytics only will be a very common use case of the SDK. So it would be great if it'll have the smallest possible footprint. @ddobrev also noted that it's important (comparing to iOS SDK binding).

**Comment by tawalke** [comment]
Hi Alexey:
Right now,  I have no details to share, given this is currently in development.

Sent from my Windows Phone
________________________________

**Comment by abfms** [comment]
Hi @tawalke,
Do you have any idea when the Amazon Mobile Analytics support might be available?

**Comment by tawalke** [comment]
It is being developed, but I do not have a definitive ETA when the team will be complete.

Sent from my Windows Phone
________________________________

**Comment by mzekrallah** [comment]
:+1: for implementing mobile analytics .. it would be really awesome to have this in aws xamarin sdk..

**Comment by tawalke** [comment]
Hi:

This Beta SDK should now be migrated to use the AWS SDK for .NET with  Xamarin has been released.  As noted, this release is under AWS SDK for .NET and is in Developer Preview.  The Xamarin SDK repo has the latest links for this update, as well as, the updates for the updated NuGet packages.

This should resolve you issue as this has the updated services like Mobile Analytics and updated desired codebase.  See links below: 
https://github.com/aws/aws-sdk-net
https://github.com/aws/aws-sdk-net#nuget-packages
